kind: Deployment
apiVersion: apps/v1beta1
metadata:
  labels:
    app: istio-test
    version: v1
  name: istio-test-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: istio-test
        version: v1
      name: istio-test
    spec:
      containers:
        - name: istio-test
          image: gcr.io/hightowerlabs/server:0.0.1
          imagePullPolicy: Always
          args:
            - "-name=istio-test-v1"
