
####  VirtualService ####

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld-virtualsvc
spec:
  hosts:
  - istio-helloworld.dev.argoproj.io
  gateways:
  - helloworld-gateway
  http:
  - route:
    - destination:
        host: helloworld-svc
        subset: v1
      weight: 80
    - destination:
        host: helloworld-svc
        subset: v2
      weight: 20

---

####  Gateway ####

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: helloworld-gateway
spec:
  # labels of istio's default controller Service in istio-system namespace
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - istio-helloworld.dev.argoproj.io
    
    
#### DestinationRule ####

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld-destination
spec:
  # service name to apply this rule to. 
  host: helloworld-svc
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
