apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-resources
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/istio-resources
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
