prometheus:
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  server:
    persistentVolume:
      size: 1Gi
    retention: 72h
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
