apiVersion: v1
kind: Service
metadata:
  labels:
    istio: ingress
  name: istio-ingress
spec:
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    istio: ingress
  type: LoadBalancer
