apiVersion: v1
kind: Service
metadata:
  labels:
    istio: pilot
  name: istio-pilot
spec:
  ports:
    - name: http-apiserver
      port: 8081
    - name: http-discovery
      port: 8080
  selector:
    istio: pilot
