apiVersion: v1
kind: Service
metadata:
  name: istio-test
  labels:
    app: istio-test
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
    protocol: TCP
  selector:
    app: istio-test
  type: NodePort
